### ISSUE TITLE
Watched User Info is from the POV of the main user

### ISSUE THREAD

**Issue by brevansio** [brevansio/PRChecker#26]
The watched user data is all based on the viewer / main user of the app. I think this misses the point of "watching" the user. 

PRs Shown:
- Currently: PRs made by the main user are filtered out
- Problem: Watched users may be reviewing a PR made by the main user
- Fix: Filter out PRs based on each watched user so cross review statuses can be seen

Status:
- Currently: The "Waiting" (also "Approved", etc) status means that the _main_ user has yet to review
- Problem: The watched user's PR list should show the status of the PR in relation to the watched user
- Fix: Modify the `OldPullRequest.viewerStatus` to use the watched user as input to filter.

What do you think?

(Note: If these changes are made, the only difference between the "normal" API and the "legacy" API will only be the `isRead` status. It doesn't really work well anyway so maybe we could remove it?)

**Comment by Ckitakishi** [comment]
> The watched user data is all based on the viewer / main user of the app. I think this misses the point of "watching" the user.

Both of these proposals are great!

> maybe we could remove `isRead`?

The `isRead` is helpful for me when checking GitHub notification, but I have no idea to make `isRead` be useful in the PR list for now..

**Comment by brevansio** [comment]
> The isRead is helpful for me when checking GitHub notification, but I have no idea to make isRead be useful in the PR list for now..

Ok, I'll keep them separate until we come up with a good way to use them
